spring.application.name=journalApp
spring.data.mongodb.uri=mongodb+srv://atujj:At9977%407@cluster0.unwhvcw.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journalb
spring.data.mongodb.auto-index-creation=true
